configfile: '../config/config.yaml'

include: 'rules/01seurat.smk' 

rule all:
    input:
#        expand("../results/01R_objects/03seurat_{region}.rds", region = config['region']),
        expand("../results/03wgcna/{region}_metacells.tsv", region = config['region'])
